### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by kpet0008** [kpet0008/u5642816_BIOL3207_Week6#1]
All for @kpet0008 , obviously
- [x] Check Q1 answer to "why should you not rely on Github as a backup?"
- [ ] Write a readme for Task 7
- [x] Find out what's wrong with markdown in Q8
- [x] Add stats to Q8 answer
- [x] Check permutations method in Q8 against previous permutations methods
